name: Propose a new component
description: Do you need a new component?
title: '🧱 '
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new component definition!
  - type: textarea
    attributes:
      label: Is your component proposal related to a problem? Please describe.
      description: Please add a clear and concise description of what the current problem is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to have.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: |
        Have you considered iterating an existing component?
        If so, please add a clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context**
      description: Add any other context or screenshots about the feature request here.
  - type: textarea
    attributes:
      label: Additional info
      description: Add any other context about the problem here.
    validations:
      required: false

