name: Improve an existing component
description: Suggest to add a new Prop, SCSS Variable and else
title: '✨'
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature improvement!
  - type: textarea
    attributes:
      label: Is your iteration request related to a problem?
      description: Do you need more flexibility in your theme? Please add a clear and concise description of what the current problem is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to achieve.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context**
      description: Add any other context or screenshots about the feature request here.
  - type: textarea
    attributes:
      label: Additional info
      description: Add any other context about the problem here.
    validations:
      required: false

