export const PIN_INPUT_ACTION_TYPES = {
  SET_PIN_INPUT_ELEMENT: Symbol('SET_PIN_INPUT_ELEMENT'),
  REMOVE_PIN_INPUT_ELEMENT: Symbol('REMOVE_PIN_INPUT_ELEMENT'),
  SET_PIN_INPUT_DISABLED: Symbol('SET_PIN_INPUT_DISABLED'),
  SET_PIN_INPUT_FOCUS: Symbol('SET_PIN_INPUT_FOCUS'),
  SET_PIN_INPUT_KEY: Symbol('SET_PIN_INPUT_KEY'),
  SET_PIN_INPUT_MASK: Symbol('SET_PIN_INPUT_MASK'),
  SET_PIN_INPUT_STATUS: Symbol('SET_PIN_INPUT_STATUS')
}

export default PIN_INPUT_ACTION_TYPES
